[tool.poetry]
name = "process-pilot"
version = "0.1.0"
description = ""
authors = ["Armes, James <james.armes@medtronic.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
