name: Process-Pilot MR Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry env use python${{ matrix.python-version }}
          poetry install
          sudo apt update
          sudo apt install graphviz -y

      - name: Lint with ruff
        run: |
          poetry run ruff check .

      - name: Test with pytest
        run: |
          poetry run pytest -vv

      - name: Build docs
        if: matrix.python-version == '3.10'
        run: |
          poetry run sphinx-build -b html docs docs/_build/html
